### ISSUE TITLE
Unwanted removal of duplicate keys on connections

### ISSUE THREAD

**Issue by Python1320** [QtPyHammer-devs/vmf_tool#13]
"connections" in test2.vmf could be modified by duplicating one of the lines.
The duplicate gets removed even if the value is not a duplicate.
Hammer editor allows multiple actions on a single entity "output".

I can provide a test that fails.

It may make sense to do something similar to https://github.com/birjolaxew/vmf-transpiler#multiple-values-per-key with a valueobject that actually expands to multiple keys when regenerating the vmf

**Comment by snake-biscuits** [comment]
Multiple connections are now loaded correctly & in the correct order
However when saving the Vmf object to file they aren't indented correctly.
I don't think stock hammer cares about that, but I haven't checked
Even if it does, I'll have that bug fixed by the end of the month as part of releasing 0.2.0 for PyPI
